"""What each Anti-nero contract DELIVERS: a study, works, or both.

The user's 1-2-3 model (2026-08-22), mirroring the sponsored-works
`deliverables` curation: (1) STUDY — the contract's object is drafting
μελέτες/Σχέδια (the 14 category-meletes contracts); (2) STUDY AND WORKS —
the design-build generation, whose own text or call states that the
contractor first drafts the studies and then executes the works they
define («η εκπόνηση από τον ανάδοχο … μελετών», «Μελέτη: … που θα
εκπονηθεί από τον Ανάδοχο»); (3) WORKS — neither: the object is works,
and any studies were made before the contract (the «με εγκεκριμένες
μελέτες» generation among them).

This is deliberately NOT a work theme: the design-build clause is the
post-2024 procurement TEMPLATE (72 of 135 cached calls), and folding it
into «Μελέτες» would flood that theme from 14 to ~115 contracts.

Emits curated khmdhs/data/contract_deliverables.json with the verbatim
clause per study_and_works contract. Deterministic; re-runnable.

Usage: .venv/Scripts/python.exe scripts/extract_deliverables.py
"""
from __future__ import annotations

import json
import re
import sqlite3
import sys
import unicodedata
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from khmdhs.config import DEFAULT_DB  # noqa: E402

CACHE = ROOT / "data" / "processed" / "pdf_cache"
OUT = ROOT / "khmdhs" / "data" / "contract_deliverables.json"

MARKER = re.compile(
    r"ΕΚΠΟΝΗΣΗ\s+ΑΠΟ\s+ΤΟΝ\s+ΑΝΑΔΟΧΟ|ΝΟΕΙΤΑΙ\s+ΕΚΑΣΤΗ\s+ΜΕΛΕΤΗ"
    r"|ΘΑ\s+ΕΚΠΟΝΗΘΕΙ\s+ΑΠΟ\s+ΤΟΝ\s+ΑΝΑΔΟΧΟ"
    r"|ΕΚΠΟΝΗΣΗ\s+ΚΑΙ\s+ΥΠΟΒΟΛΗ\s+ΑΠΟ\s+ΤΟΝ\s+ΑΝΑΔΟΧΟ")


def fold(s: str) -> str:
    """1:1 per-character fold (accent stripped per char), so a match offset
    in the folded text cuts a VERBATIM excerpt from the original."""
    out = []
    for ch in (s or ""):
        d = unicodedata.normalize("NFD", ch.upper())
        base = next((c for c in d if not unicodedata.combining(c)), ch)
        out.append(base)
    return "".join(out)


def excerpt_at(text: str, at: int, width: int = 150) -> str:
    frag = text[max(0, at - 30):at + width]
    return "… " + " ".join(frag.split()) + " …"


def find_marker(path: Path) -> str | None:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    f = fold(text)
    m = MARKER.search(f)
    if m is None:
        return None
    return excerpt_at(text, m.start())   # fold is 1:1 — offsets carry over


def main() -> int:
    kh = sqlite3.connect(DEFAULT_DB)
    kh.row_factory = sqlite3.Row
    scope = [r[0] for r in kh.execute(
        "SELECT reference_number FROM contract_scope WHERE in_scope=1"
        " ORDER BY reference_number")]
    cats = {r[0]: (r[1], r[2]) for r in kh.execute(
        "SELECT reference_number, category, title FROM contract_categories")}

    out: dict = {
        "_doc": ("What each in-scope contract DELIVERS — study / works / "
                 "study_and_works — the user's 1-2-3 model of 2026-08-22 "
                 "(DATA_DECISIONS). study = the 14 category-meletes contracts; "
                 "study_and_works = the design-build clause found in the "
                 "contract's own text or its call (verbatim excerpt kept); "
                 "works = neither. Regenerated by "
                 "scripts/extract_deliverables.py; _overrides wins per ΑΔΑΜ."),
        "_kinds": {
            "study": {"el": "Μελέτη", "en": "Study"},
            "study_and_works": {"el": "Μελέτη και έργο",
                                "en": "Study and works"},
            "works": {"el": "Έργο", "en": "Works"},
        },
        "_overrides": (json.loads(OUT.read_text(encoding="utf-8"))
                       .get("_overrides", {}) if OUT.exists() else {}),
    }
    counts = {"study": 0, "study_and_works": 0, "works": 0}
    for ref in scope:
        cat, _title = cats.get(ref, (None, None))
        if cat == "meletes":
            entry = {"kind": "study", "source": "category",
                     "excerpt": None,
                     "note": "the curated category: the object is the studies"}
        else:
            ex = find_marker(CACHE / f"{ref}.txt")
            src = "pdf"
            if ex is None:
                for r in kh.execute(
                        "SELECT DISTINCT adam FROM contract_families"
                        " WHERE reference_number=? AND kind='notice'", (ref,)):
                    ex = find_marker(CACHE / f"{r[0]}.txt")
                    if ex:
                        src = f"call:{r[0]}"
                        break
            if ex:
                entry = {"kind": "study_and_works", "source": src,
                         "excerpt": ex, "note": None}
            else:
                entry = {"kind": "works", "source": None, "excerpt": None,
                         "note": None}
        counts[entry["kind"]] += 1
        out[ref] = entry

    for ref, e in out["_overrides"].items():
        out[ref] = {**out.get(ref, {}), **e}
    out["_curated_at"] = date.today().isoformat()
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1),
                   encoding="utf-8")
    print(counts, "->", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
